### ISSUE TITLE
分析报告时报错，导致idea中报告无法显示，但是sonar上报告可正常显示，idea版本2020.3.4

### ISSUE THREAD

**Issue by jackkkyyy** [lowkeyfish/sonar-intellij-plugin#10]
ERROR: 报告解析出错, java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.yujunyang.intellij.plugin.sonar.core.LogOutputImpl.log(LogOutputImpl.java:81)
	at org.sonarsource.scanner.api.EmbeddedScanner.lambda$doExecute$0(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.internal.batch.DefaultBatchFactory.lambda$createBatch$0(DefaultBatchFactory.java:36)
	at org.sonar.batch.bootstrapper.LogCallbackAppender.append(LogCallbackAppender.java:41)
	at org.sonar.batch.bootstrapper.LogCallbackAppender.append(LogCallbackAppender.java:27)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
	at ch.qos.logback.classic.Logger.info(Logger.java:587)
	at org.sonar.api.utils.log.LogbackLogger.doInfo(LogbackLogger.java:100)
	at org.sonar.api.utils.log.BaseLogger.info(BaseLogger.java:88)
	at org.sonar.scanner.report.ReportPublisher.generateReportFile(ReportPublisher.java:155)
	at org.sonar.scanner.report.ReportPublisher.execute(ReportPublisher.java:138)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:366)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy318.execute(null:-1)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at com.yujunyang.intellij.plugin.sonar.core.EmbeddedScannerHelper.startEmbeddedScanner(EmbeddedScannerHelper.java:92)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.asyncStartImpl(SonarScannerStarter.java:242)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.asyncStart(SonarScannerStarter.java:220)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.access$000(SonarScannerStarter.java:54)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter$2.run(SonarScannerStarter.java:201)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.security.AccessController.doPrivileged(AccessController.java:-2)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.lang.Thread.run(Thread.java:834)
	
	Caused by: java.lang.NullPointerException: null
	at com.yujunyang.intellij.plugin.sonar.api.SonarApiImpl.getDefaultProfiles(SonarApiImpl.java:73)
	at com.yujunyang.intellij.plugin.sonar.api.SonarApiImpl.getRules(SonarApiImpl.java:86)
	at com.yujunyang.intellij.plugin.sonar.core.Report.getRules(Report.java:284)
	at com.yujunyang.intellij.plugin.sonar.core.Report.analyze(Report.java:105)
	at com.yujunyang.intellij.plugin.sonar.core.Report.<init>(Report.java:69)
	at com.yujunyang.intellij.plugin.sonar.core.ReportUtils.lambda$createReport$0(ReportUtils.java:68)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:875)
	at com.yujunyang.intellij.plugin.sonar.core.ReportUtils.createReport(ReportUtils.java:65)
	at com.yujunyang.intellij.plugin.sonar.core.LogOutputImpl.lambda$log$0(LogOutputImpl.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.lang.Thread.run(Thread.java:834)

**Comment by jackkkyyy** [comment]
公司sonarQube是通过域名加服务名访问的，例如：http://www.abc.com/sonarqube，如果配置的url是域名加服务名，如下图
<img width="445" alt="image" src="https://user-images.githubusercontent.com/46160662/164357173-1553457e-ec62-4e40-8e50-89ca9b519055.png">

再调用SonarApi类中的方法时，会丢掉服务名，将SonarApi中的接口地址加上对应服务名即可。
<img width="973" alt="image" src="https://user-images.githubusercontent.com/46160662/164357023-1af943cd-688b-4494-8033-0e0cac85811a.png">

如果url中不配置服务名，调用其他接口会出错，希望作者可以适配一下，谢谢。

**Comment by thierrychhuon-artk** [comment]
Hello, i'm getting the same error. The error seems to happened when the report is parsed.

INFO: Start parsing report
ERROR: Failed to parse report, java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.yujunyang.intellij.plugin.sonar.core.LogOutputImpl.log(LogOutputImpl.java:81)
	at org.sonarsource.scanner.api.EmbeddedScanner.lambda$doExecute$0(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.internal.batch.DefaultBatchFactory.lambda$createBatch$0(DefaultBatchFactory.java:36)
	at org.sonar.batch.bootstrapper.LogCallbackAppender.append(LogCallbackAppender.java:27)
	at org.sonar.batch.bootstrapper.LogCallbackAppender.append(LogCallbackAppender.java:13)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
	at ch.qos.logback.classic.Logger.info(Logger.java:587)
	at org.sonar.api.utils.log.LogbackLogger.doInfo(LogbackLogger.java:100)
	at org.sonar.api.utils.log.BaseLogger.info(BaseLogger.java:88)
	at org.sonar.scanner.report.ReportPublisher.generateReportFile(ReportPublisher.java:184)
	at org.sonar.scanner.report.ReportPublisher.execute(ReportPublisher.java:154)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:408)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:123)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:109)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:128)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:123)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:109)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:58)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:52)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy389.execute(null:-1)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at com.yujunyang.intellij.plugin.sonar.core.EmbeddedScannerHelper.startEmbeddedScanner(EmbeddedScannerHelper.java:92)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.asyncStartImpl(SonarScannerStarter.java:242)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.asyncStart(SonarScannerStarter.java:220)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.access$000(SonarScannerStarter.java:54)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter$2.run(SonarScannerStarter.java:201)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.security.AccessController.doPrivileged(AccessController.java:-2)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.lang.Thread.run(Thread.java:829)
	
	Caused by: java.lang.NullPointerException: null
	at com.yujunyang.intellij.plugin.sonar.api.SonarApiImpl.getDefaultProfiles(SonarApiImpl.java:73)
	at com.yujunyang.intellij.plugin.sonar.api.SonarApiImpl.getRules(SonarApiImpl.java:86)
	at com.yujunyang.intellij.plugin.sonar.core.Report.getRules(Report.java:284)
	at com.yujunyang.intellij.plugin.sonar.core.Report.analyze(Report.java:105)
	at com.yujunyang.intellij.plugin.sonar.core.Report.<init>(Report.java:69)
	at com.yujunyang.intellij.plugin.sonar.core.ReportUtils.lambda$createReport$0(ReportUtils.java:68)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at com.yujunyang.intellij.plugin.sonar.core.ReportUtils.createReport(ReportUtils.java:65)
	at com.yujunyang.intellij.plugin.sonar.core.LogOutputImpl.lambda$log$0(LogOutputImpl.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.lang.Thread.run(Thread.java:829)

Hope you could fix that, your plugin seems pretty usefull !

**Comment by davidlewine** [comment]
Same error as above.

**Comment by crenshawdk** [comment]
same. seems like this plugin is dead though:(

Version 0.2.2
intellij 2022.3.2

**Comment by awoter** [comment]
一样情况，执行分析的时候报错，且不显示报告信息
报错日志如下：
`Sonar analysis start...
Analyze scope: Selected files
	/Users/pavee/IdeaProjects/xxx/xxx/xxx/xxx/AbstractWarmupService.java


INFO: Start build project [xxx-xxx-xxx-svc]
DEBUG: keyStore is : 
DEBUG: keyStore type is : pkcs12
DEBUG: keyStore provider is : 
DEBUG: init keystore
DEBUG: init keymanager of type SunX509
DEBUG: Create: /Users/xxxx/.sonar/cache
INFO: User cache: /Users/xxxx/.sonar/cache
DEBUG: Create: /Users/xxxx/.sonar/cache/_tmp
DEBUG: Extract sonar-scanner-api-batch in temp...
DEBUG: Get bootstrap index...
DEBUG: Download: http://sonarqube-pre.xxxxx.work/batch/index
DEBUG: Get bootstrap completed
DEBUG: Create isolated classloader...
DEBUG: Start temp cleaning...
DEBUG: Temp cleaning done
INFO: Default locale: "zh_CN_#Hans", source code encoding: "UTF-8"
DEBUG: Work directory: /Users/xxxx/xxxx/xxxx/.idea/SonarAnalyzer/.scannerwork
DEBUG: Execution execute
INFO: Load global settings
INFO: Load global settings (done) | time=73ms
INFO: Server id: 39229B73-AYMWh3Rb00EGfB-5QpJs
INFO: User cache: /Users/pavee/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=31ms
INFO: Plugin [l10nzh] defines 'l10nen' as base plugin. This metadata can be removed from manifest of l10n plugins since version 5.2.
INFO: Load/download plugins (done) | time=72ms
INFO: Process project properties
INFO: Execute project builders
INFO: Execute project builders (done) | time=1ms
INFO: Project key: SonarAnalyzer:xxxxxxx
INFO: Base dir: /Users/xxxx/IdeaProjects/xxxxx
INFO: Working dir: /xxxxx/xxxx/xxx/.idea/SonarAnalyzer/.scannerwork
INFO: Load project settings for component key: 'SonarAnalyzer:xxxx'
INFO: Load project settings for component key: 'SonarAnalyzer:xxxx' (done) | time=30ms
INFO: Load project branches
INFO: Load project branches (done) | time=31ms
INFO: Load project pull requests
INFO: Load project pull requests (done) | time=21ms
INFO: Load branch configuration
INFO: Load branch configuration (done) | time=0ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=178ms
INFO: Load active rules
INFO: Load active rules (done) | time=14558ms
INFO: Indexing files...
INFO: Project configuration:
INFO: 1 file indexed
INFO: 0 files ignored because of scm ignore settings
INFO: Quality profile for java: p3c+pmd
INFO: ------------- Run sensors on module SonarAnalyzer:xxxxxx
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=21ms
INFO: Sensor JavaSquidSensor [java]
INFO: Configured Java source version (sonar.java.source): 8
INFO: JavaClasspath initialization
INFO: JavaClasspath initialization (done) | time=7ms
INFO: JavaTestClasspath initialization
INFO: JavaTestClasspath initialization (done) | time=0ms
INFO: Java Main Files AST scan
INFO: 1 source files to be analyzed
INFO: Load project repositories
INFO: Load project repositories (done) | time=173ms
INFO: 1/1 source files have been analyzed
INFO: Java Main Files AST scan (done) | time=332ms
INFO: Java Test Files AST scan
INFO: 0 source files to be analyzed
INFO: Java Test Files AST scan (done) | time=0ms
INFO: 0/0 source files have been analyzed
INFO: Sensor JavaSquidSensor [java] (done) | time=851ms
INFO: Sensor PmdSensor [pmd]
INFO: Execute PMD 6.15.0
INFO: Java version: 1.8
INFO: PMD configuration: /Users/xxxx/xxxx/xxxx/.idea/SonarAnalyzer/.scannerwork/pmd.xml
INFO: Execute PMD 6.15.0 (done) | time=540ms
INFO: Sensor PmdSensor [pmd] (done) | time=543ms
INFO: Sensor SurefireSensor [java]
INFO: parsing [/Users/xxxx/xxxx/xxxx/target/surefire-reports]
INFO: Sensor SurefireSensor [java] (done) | time=1ms
INFO: Sensor JaCoCoSensor [java]
INFO: Sensor JaCoCoSensor [java] (done) | time=0ms
INFO: Sensor JavaXmlSensor [java]
INFO: Sensor JavaXmlSensor [java] (done) | time=0ms
INFO: Sensor HTML [web]
INFO: Sensor HTML [web] (done) | time=5ms
INFO: Sensor Infer Java [swift]
INFO: Sensor Infer Java [swift] (done) | time=4ms
INFO: Sensor JaCoCo XML Report Importer [jacoco]
INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=1ms
INFO: ------------- Run sensors on project
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=2ms
INFO: Sensor Java CPD Block Indexer
INFO: Sensor Java CPD Block Indexer (done) | time=4ms
INFO: Calculating CPD for 1 file
INFO: CPD calculation finished
INFO: 开始复制报告
INFO: 报告复制成功
INFO: 开始解析报告
ERROR: 报告解析出错, java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.yujunyang.intellij.plugin.sonar.core.LogOutputImpl.log(LogOutputImpl.java:81)
	at org.sonarsource.scanner.api.EmbeddedScanner.lambda$doExecute$0(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.internal.batch.DefaultBatchFactory.lambda$createBatch$0(DefaultBatchFactory.java:36)
	at org.sonar.batch.bootstrapper.LogCallbackAppender.append(LogCallbackAppender.java:41)
	at org.sonar.batch.bootstrapper.LogCallbackAppender.append(LogCallbackAppender.java:27)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
	at ch.qos.logback.classic.Logger.info(Logger.java:587)
	at org.sonar.api.utils.log.LogbackLogger.doInfo(LogbackLogger.java:100)
	at org.sonar.api.utils.log.BaseLogger.info(BaseLogger.java:88)
	at org.sonar.scanner.report.ReportPublisher.generateReportFile(ReportPublisher.java:155)
	at org.sonar.scanner.report.ReportPublisher.execute(ReportPublisher.java:138)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:366)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at jdk.proxy55.$Proxy449.execute(null:-1)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at com.yujunyang.intellij.plugin.sonar.core.EmbeddedScannerHelper.startEmbeddedScanner(EmbeddedScannerHelper.java:92)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.asyncStartImpl(SonarScannerStarter.java:242)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.asyncStart(SonarScannerStarter.java:220)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.access$000(SonarScannerStarter.java:54)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter$2.run(SonarScannerStarter.java:201)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.lang.Thread.run(Thread.java:833)
	
	Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at com.yujunyang.intellij.plugin.sonar.core.Report.analyze(Report.java:122)
	at com.yujunyang.intellij.plugin.sonar.core.Report.<init>(Report.java:69)
	at com.yujunyang.intellij.plugin.sonar.core.ReportUtils.lambda$createReport$0(ReportUtils.java:68)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.yujunyang.intellij.plugin.sonar.core.ReportUtils.createReport(ReportUtils.java:65)
	at com.yujunyang.intellij.plugin.sonar.core.LogOutputImpl.lambda$log$0(LogOutputImpl.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.lang.Thread.run(Thread.java:833)
INFO: Analysis report generated in 40ms, dir size=761 KB
INFO: Analysis report compressed in 33ms, zip size=93 KB
INFO: Analysis report uploaded in 76ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://sonarqube.xxxxx.xxxxx/dashboard?id=SonarAnalyzer%3Axxxxxx
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at http://sonarqube.xxxxx.xxxxx/api/ce/task?id=xxxxxxxx
INFO: Executing post-job 'Final report'
INFO: Turn debug info on to get more details (sonar-scanner -X -Dsonar.verbose=true ...).
INFO: Executing post-job 'Final report'
INFO: Turn debug info on to get more details (sonar-scanner -X -Dsonar.verbose=true ...).
INFO: Analysis total time: 17.992 s

Sonar analysis finished
`
报告信息完全为空：
![image](https://github.com/lowkeyfish/sonar-intellij-plugin/assets/4442838/0db64dba-a90d-4672-8ccc-f52d6768d05b)

IDEA版本：
IntelliJ IDEA 2023.2.3 (Community Edition)
![image](https://github.com/lowkeyfish/sonar-intellij-plugin/assets/4442838/8428091f-c91e-4a34-91a4-68aa4523e254)
