### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by crenshawdk** [lowkeyfish/sonar-intellij-plugin#14]
Im getting this while analyzing 
version 0.2.2
intellij 2022.3.2

ERROR: Failed to parse report, java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.yujunyang.intellij.plugin.sonar.core.LogOutputImpl.log(LogOutputImpl.java:81)
	at org.sonarsource.scanner.api.EmbeddedScanner.lambda$doExecute$0(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.internal.batch.DefaultBatchFactory.lambda$createBatch$0(DefaultBatchFactory.java:36)
	at org.sonar.batch.bootstrapper.LogCallbackAppender.append(LogCallbackAppender.java:41)
	at org.sonar.batch.bootstrapper.LogCallbackAppender.append(LogCallbackAppender.java:27)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
	at ch.qos.logback.classic.Logger.info(Logger.java:587)
	at org.sonar.api.utils.log.LogbackLogger.doInfo(LogbackLogger.java:100)
	at org.sonar.api.utils.log.BaseLogger.info(BaseLogger.java:88)
	at org.sonar.scanner.report.ReportPublisher.generateReportFile(ReportPublisher.java:175)
	at org.sonar.scanner.report.ReportPublisher.execute(ReportPublisher.java:149)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:376)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:137)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at jdk.proxy314.$Proxy1913.execute(null:-1)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at com.yujunyang.intellij.plugin.sonar.core.EmbeddedScannerHelper.startEmbeddedScanner(EmbeddedScannerHelper.java:92)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.asyncStartImpl(SonarScannerStarter.java:242)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.asyncStart(SonarScannerStarter.java:220)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter.access$000(SonarScannerStarter.java:54)
	at com.yujunyang.intellij.plugin.sonar.core.SonarScannerStarter$2.run(SonarScannerStarter.java:201)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.lang.Thread.run(Thread.java:833)
	
	Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at com.yujunyang.intellij.plugin.sonar.core.Report.analyze(Report.java:122)
	at com.yujunyang.intellij.plugin.sonar.core.Report.<init>(Report.java:69)
	at com.yujunyang.intellij.plugin.sonar.core.ReportUtils.lambda$createReport$0(ReportUtils.java:68)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at com.yujunyang.intellij.plugin.sonar.core.ReportUtils.createReport(ReportUtils.java:65)
	at com.yujunyang.intellij.plugin.sonar.core.LogOutputImpl.lambda$log$0(LogOutputImpl.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.lang.Thread.run(Thread.java:833)
INFO: Analysis report generated in 721ms, dir size=1.4 MB

**Comment by awoter** [comment]
@crenshawdk 这个问题还存在啊，刚下载你的插件分析也是一样报这个错，麻烦修复下
